---
- name: Install and Start Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: "0755"

    - name: Delete existing Minikube cluster (if any)
      shell: minikube delete --all --purge
      ignore_errors: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Set sysctl for Minikube lock
      sysctl:
        name: fs.protected_regular
        value: 0
        state: present

    - name: Ensure Jenkins user is added to the Docker group
      command: usermod -aG docker jenkins
      ignore_errors: yes

    - name: Restart Docker to apply group changes
      service:
        name: docker
        state: restarted

    - name: Start Minikube with Docker driver
      become: no
      shell: |
        minikube start \
          --driver=docker \
          --cpus=2 \
          --memory=2048mb \
          --force
      environment:
        HOME: "/var/jenkins_home"

