---
- name: Install and Start Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - conntrack

    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: "0755"

    - name: Delete existing Minikube cluster (if any)
      command: minikube delete --all --purge
      ignore_errors: yes

    - name: Set sysctl to disable fs.protected_regular
      shell: |
        sysctl fs.protected_regular=0
      become: true

    - name: Check if Docker service is active
      shell: |
        systemctl is-active docker || systemctl start docker
      register: docker_status
      changed_when: docker_status.rc == 0
      failed_when: docker_status.rc != 0

    - name: Start Minikube
      become: false
      shell: |
        minikube start --driver=docker --cpus=2 --memory=2048mb --docker-opt="--network=jenkins-minikube-net" --force -v=8
      environment:
        HOME: "/var/jenkins_home"

    - name: Check Minikube status
      shell: minikube status
      register: minikube_status
      failed_when: "'host: Running' not in minikube_status.stdout"
