- name: Install and Start Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: "0755"

    - name: Delete existing Minikube cluster
      command: minikube delete --all --purge
      ignore_errors: yes

    - name: Create Jenkins-Minikube network
      shell: docker network create --driver bridge jenkins-minikube-net || true

    - name: Connect Jenkins and Minikube containers to the network
      shell: >
        docker network connect jenkins-minikube-net jenkins;
        docker network connect jenkins-minikube-net minikube;

    - name: Start Minikube
      shell: >
        minikube start
        --driver=docker
        --force
        --cpus=2
        --memory=2048mb
        --docker-opt="--network=jenkins-minikube-net"
        --apiserver-ips="172.18.0.3"
        --apiserver-name="minikube.local"
        -v=8
      environment:
        HOME: "/var/jenkins_home"

