- name: Install and Start Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: "0755"

    - name: Delete existing Minikube cluster
      command: minikube delete --all --purge
      ignore_errors: yes

    - name: Set fs.protected_regular to 0
      shell: sysctl -w fs.protected_regular=0
      ignore_errors: yes

    - name: Create Jenkins-Minikube network
      shell: docker network create --driver bridge jenkins-minikube-net || true

    - name: Connect Jenkins container to network
      shell: docker network connect jenkins-minikube-net jenkins || true

    - name: Start Minikube
      shell: >
        minikube start
        --driver=docker
        --force
        --cpus=2
        --memory=2048mb
        --docker-opt="--network=jenkins-minikube-net"
        -v=8
      environment:
        HOME: "/var/jenkins_home"
      register: minikube_start
      ignore_errors: yes

    - name: Debug Minikube start logs if start fails
      debug:
        msg: "{{ minikube_start.stderr }}"
      when: minikube_start.failed

    - name: Ensure Minikube container exists
      shell: minikube start --driver=docker --force --memory=2048mb --cpus=2
      register: minikube_check
      changed_when: false

    - name: Connect Minikube container to Jenkins-Minikube network
      shell: |
        docker network inspect jenkins-minikube-net | grep '\\"Name\\": \\"minikube\\"' || docker network connect jenkins-minikube-net minikube
      ignore_errors: yes

    - name: Check Minikube profiles
      shell: minikube profile list
      register: minikube_profiles
      changed_when: false

    - name: Debug Minikube profiles
      debug:
        msg: "{{ minikube_profiles.stdout }}"
