---
- name: Install and Start Minikube
  hosts: localhost
  become: true

  tasks:
    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Delete existing Minikube cluster (if any)
      shell: minikube delete || true

    - name: Check if fs.protected_regular is already 0
      command: sysctl fs.protected_regular
      register: sysctl_check
      ignore_errors: true

    - name: Set sysctl for Minikube lock (if needed)
      command: sysctl fs.protected_regular=0
      when: "'fs.protected_regular = 0' not in sysctl_check.stdout"
      ignore_errors: true

    - name: Start Minikube
      command: minikube start --driver=docker --force

